### PR TITLE
Fix all tests to pass valgrind's leak checks

### LINKED ISSUE #160: Potential memory leak in PresetExtractor
Code:

```
if(xml.enterbranch(type) == 0)
        return;
```

This does not delete the previously allocated `t`.

### PR DESCRIPTION
**Pull request by JohannesLorenz**
Now ready to review.
Should not be anything new after the IRC discussions.

Fixes #160

### CODE REVIEW

File: src/Misc/PresetExtractor.cpp [hunk 1]
```diff
@@ -227,7 +227,10 @@ void doPaste(MiddleWare &mw, string url, string type, XMLwrapper &xml, Ts&&... a
         type = "Plfo";
 
     if(xml.enterbranch(type) == 0)
+    {
+        delete t;
```
Comment (fundamental) [inline src/Misc/PresetExtractor.cpp:231]: Same comment applies to the old code, but should we consider this a bug if we ever get to this return statement?

File: src/Tests/MiddlewareTest.cpp [hunk 2]
```diff
@@ -60,16 +61,21 @@ class PluginTest
                 middleware[i] = new MiddleWare(std::move(*synth), &config);
                 master[i] = middleware[i]->spawnMaster();
                 //printf("Octave size = %d\n", master[i]->microtonal.getoctavesize());
+                if (i != NUM_MIDDLEWARE-1) {
+                    delete synth;
```
Comment (fundamental) [inline src/Tests/MiddlewareTest.cpp:65]: This is required even with the std::move? I tend to forget some of those semantics.

**Comment by fundamental** [comment]
Perhaps a few extra free methods for the various zyn types, but no harm other than a few extra ms during the build phase. Just confirm that the std::move(*synth) delete looks right to you on a second glance I'm I'd say let's merge this.

File: src/Tests/MiddlewareTest.cpp (hunk 2 above)
Comment (JohannesLorenz) [reply src/Tests/MiddlewareTest.cpp:65]: [Moving an object does not change its lifetime](https://stackoverflow.com/questions/15663539/why-isnt-object-returned-by-stdmove-destroyed-immediately). Compare it with an `std::vector` that you have on the stack - the move only alters its pointers. After you move from it, the memory is still there. Same with a vector (or `SYNTH_T`) on heap.

Aside from the theory, I could see with valgrind that this fixed a leak.

File: src/Misc/PresetExtractor.cpp (hunk 1 above)
Comment (JohannesLorenz) [reply src/Misc/PresetExtractor.cpp:231]: I think so, but what is our way to handle bugs? Should zyn exit just because of a failed paste?

Another thing we could do is print a message on `return`ing, so that the problem is revealed.

File: src/Tests/MiddlewareTest.cpp (hunk 2 above)
Comment (fundamental) [reply src/Tests/MiddlewareTest.cpp:65]: Works for me, merging now.
